import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import crypto from 'crypto';
const env = Object.fromEntries(readFileSync('.env','utf8').split('\n').filter(l=>l.includes('=')).map(l=>{const i=l.indexOf('=');return [l.slice(0,i), l.slice(i+1).replace(/^"|"$/g,'')]}));
const OWNER='rt-'+crypto.randomBytes(4).toString('hex');
const fp=crypto.createHash('sha256').update(OWNER).digest('hex');
const c=createClient(env.VITE_SUPABASE_URL, env.VITE_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false},global:{headers:{'x-owner-key':OWNER}}});
let all=0, filtered=0;
c.channel('a').on('postgres_changes',{event:'*',schema:'public',table:'sync_events'},p=>{all++;console.log('ANY event', p.eventType, p.new?.operation, p.new?.owner_fingerprint?.slice(0,8));}).subscribe(s=>console.log('chan a:',s));
c.channel('b').on('postgres_changes',{event:'INSERT',schema:'public',table:'sync_events',filter:`owner_fingerprint=eq.${fp}`},()=>{filtered++;}).subscribe(s=>console.log('chan b:',s));
await new Promise(r=>setTimeout(r,4000));
const pu='https://www.linkedin.com/in/rt-'+Date.now();
const ins=await c.from('contacts').insert({owner_key:OWNER,full_name:'RT',profile_url:pu}).select('id').single();
console.log('insert:',ins.error?.message||'ok');
await new Promise(r=>setTimeout(r,4000));
console.log('events any:',all,'filtered:',filtered);
console.log('fingerprint expected:', fp.slice(0,8));
const ev=await c.from('sync_events').select('owner_fingerprint,operation').order('id',{ascending:false}).limit(3);
console.log('rows in sync_events:', JSON.stringify(ev.data), ev.error?.message||'');
await c.from('contacts').delete().eq('id',ins.data?.id);
process.exit(0);
